name: Trigger auto deployment for llm-inference-apps

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/llm-inference-apps-AutoDeployTrigger-d9c19778-d6f8-447b-9bd6-b14995d87134.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: weisshornregistry0003.azurecr.io
          username: ${{ secrets.LLMINFERENCEAPPS_REGISTRY_USERNAME }}
          password: ${{ secrets.LLMINFERENCEAPPS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: weisshornregistry0003.azurecr.io/llm-inference-apps-web:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LLMINFERENCEAPPS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n llm-inference-apps -g rg-resource-group-0003 --server weisshornregistry0003.azurecr.io --username  ${{ secrets.LLMINFERENCEAPPS_REGISTRY_USERNAME }} --password ${{ secrets.LLMINFERENCEAPPS_REGISTRY_PASSWORD }}
            az containerapp update -n llm-inference-apps -g rg-resource-group-0003 --image weisshornregistry0003.azurecr.io/llm-inference-apps-web:${{ github.sha }}
