# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - app-llm-inference-apps-web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://weisshornregistry0003.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_0e6c77c436574da081baa1c928f77d56 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_432ae301a69a405f8ee0441c12095046 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: weisshornregistry0003.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0e6c77c436574da081baa1c928f77d56 }}/llm-inference-apps-web:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'app-llm-inference-apps-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cfc52fd7f0c940a5bcb663a2674b141b }}
        images: 'weisshornregistry0003.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_0e6c77c436574da081baa1c928f77d56 }}/llm-inference-apps-web:${{ github.sha }}'